# D experiment
# YOLOv8n + CondConv + FReLU + P2 detection head + Wise-IoU

nc: 10
depth_multiple: 0.33
width_multiple: 0.25

backbone:
  # [from, repeats, module, args]
  - [-1, 1, CondConv, [64, 3, 2]]      # 0-P1/2
  - [-1, 1, CondConv, [128, 3, 2]]     # 1-P2/4
  - [-1, 3, C2f, [128, True]]          # 2-P2/4
  - [-1, 1, CondConv, [256, 3, 2]]     # 3-P3/8
  - [-1, 6, C2f, [256, True]]          # 4-P3/8
  - [-1, 1, CondConv, [512, 3, 2]]     # 5-P4/16
  - [-1, 6, C2f, [512, True]]          # 6-P4/16
  - [-1, 1, CondConv, [1024, 3, 2]]    # 7-P5/32
  - [-1, 3, C2f, [1024, True]]         # 8-P5/32
  - [-1, 1, SPPF, [1024, 5]]           # 9

head:
  - [-1, 1, nn.Upsample, [None, 2, nearest]]
  - [[-1, 6], 1, Concat, [1]]
  - [-1, 3, C2f, [512]]                # 12-P4/16

  - [-1, 1, nn.Upsample, [None, 2, nearest]]
  - [[-1, 4], 1, Concat, [1]]
  - [-1, 3, C2f, [256]]                # 15-P3/8

  - [-1, 1, nn.Upsample, [None, 2, nearest]]
  - [[-1, 2], 1, Concat, [1]]
  - [-1, 3, C2f, [128]]                # 18-P2/4

  - [-1, 1, CondConv, [128, 3, 2]]
  - [[-1, 15], 1, Concat, [1]]
  - [-1, 3, C2f, [256]]                # 21-P3/8

  - [-1, 1, CondConv, [256, 3, 2]]
  - [[-1, 12], 1, Concat, [1]]
  - [-1, 3, C2f, [512]]                # 24-P4/16

  - [-1, 1, CondConv, [512, 3, 2]]
  - [[-1, 9], 1, Concat, [1]]
  - [-1, 3, C2f, [1024]]               # 27-P5/32

  - [[18, 21, 24, 27], 1, Detect, [nc]]  # Detect(P2, P3, P4, P5)
